using System.Text;

namespace SpecScribe;

/// <summary>Wraps rendered markdown bodies in full HTML pages, and builds the generated site's index.</summary>
public static class HtmlTemplater
{

    public static string RenderPage(DocModel doc, SiteNav nav, EntityPager? pager = null)
    {
        var prefix = PathUtil.RelativePrefix(doc.OutputRelativePath);
        var cssHref = prefix + ForgeOptions.StylesheetName;
        var scriptHref = prefix + ForgeOptions.ScriptName;

        var sb = new StringBuilder();
        sb.Append(PathUtil.RenderHeadOpen(
            $"{doc.Title} — {nav.SiteTitle}", cssHref, scriptHref,
            $"{doc.Title} — living documentation for {nav.SiteTitle}, generated by SpecScribe."));
        sb.Append(nav.RenderNavBar(doc.OutputRelativePath));
        sb.Append(SiteNav.RenderBreadcrumb(doc.OutputRelativePath, new (string, string?)[] { ("Home", "index.html"), (doc.Title, null) }));

        // Main content (header + article) is composed separately so it can be wrapped in the two-column page
        // shell alongside the TOC sidebar. Source render order equals DocModel.Headings order for a straight
        // full-page render, so those headings feed the shared TOC seam directly.
        var main = new StringBuilder();
        main.Append("<header class=\"doc-header\">\n");
        // Sibling pager (ADR record pages pass one; every other doc passes null → byte-identical). Absolute-positioned,
        // so emitting it first in source does not shift the centered kicker/title flow. [Prev/next navigation]
        main.Append(pager?.Render());
        main.Append($"  <h1>{Html(doc.Title)}</h1>\n");
        if (doc.Frontmatter.Project is { Length: > 0 } project)
        {
            main.Append($"  <div class=\"doc-subtitle\">{Html(project)}</div>\n");
        }
        main.Append("  <div class=\"meta-pills\">\n");
        AppendPill(main, doc.Frontmatter.Author, "author");
        AppendPill(main, doc.Frontmatter.Date, "date");
        AppendPill(main, doc.Frontmatter.Version, v => $"v{v}");
        AppendStatusPill(main, doc.Frontmatter.Status);
        main.Append($"    <span class=\"pill\">{Html(PathUtil.NormalizeSlashes(doc.SourceRelativePath))}</span>\n");
        main.Append("  </div>\n</header>\n\n");

        // Spec-kernel bodies get the Capabilities list restyled into scannable cards; every other page's body
        // passes through untouched (the styler no-ops without the authored CAP pattern anyway). [Story 2.2 polish]
        var bodyHtml = IsSpecKernelPage(doc) ? CapabilityStyler.Style(doc.BodyHtml) : doc.BodyHtml;
        main.Append("<article class=\"doc-body\">\n");
        main.Append(bodyHtml);
        main.Append("\n</article>\n");

        var tocEntries = doc.Headings
            .Where(h => h.Level is 2 or 3)
            .Select(h => new Toc.Entry(h.Level, h.Text, h.Id))
            .ToList();
        sb.Append("<main id=\"main-content\">\n");
        // The companion-docs cross-link block (spec-kernel pages only) rides in the sidebar rail beneath the
        // TOC, not the content column, so it reads as a related-docs sidebar. [Story 2.2 polish]
        sb.Append(Toc.WrapWithSidebar(main.ToString(), tocEntries, BuildCompanionRail(doc)));
        sb.Append("</main>\n\n");

        sb.Append(PathUtil.RenderFooter(PathUtil.RelativePrefix(doc.OutputRelativePath)));
        if (doc.HasMermaid)
        {
            sb.Append(Mermaid.InitScript());
        }
        sb.Append("</body>\n</html>\n");
        return sb.ToString();
    }

    /// <summary>True for a page generated from a doc under the <c>specs/</c> kernel directory — the pages that
    /// get the capability-card and companion-rail treatment. Keyed by directory, disjoint from Story 2.1's
    /// <c>implementation-artifacts/spec-*.md</c>. [Story 2.2 polish]</summary>
    private static bool IsSpecKernelPage(DocModel doc) =>
        PathUtil.NormalizeSlashes(doc.SourceRelativePath).StartsWith("specs/", StringComparison.OrdinalIgnoreCase);

    /// <summary>Builds the "Companion documents" related-docs nav for the sidebar rail from a spec page's
    /// resolved companions, or null when there are none (so the rail shows only the TOC, or nothing). Each
    /// entry was resolved to a real generated page by the SiteGenerator — never a broken link. [Story 2.2 polish]</summary>
    private static string? BuildCompanionRail(DocModel doc)
    {
        if (doc.Companions.Count == 0) return null;

        var sb = new StringBuilder();
        sb.Append("<nav class=\"companion-docs\" aria-label=\"Companion documents\">\n");
        sb.Append("  <span class=\"companion-label\">Companion documents</span>\n");
        sb.Append("  <ul>\n");
        foreach (var (label, href) in doc.Companions)
        {
            sb.Append($"    <li><a href=\"{Html(href)}\">{Html(label)}</a></li>\n");
        }
        sb.Append("  </ul>\n</nav>\n");
        return sb.ToString();
    }

    /// <summary>Whether a top-level source folder is one of the well-known home-index groups — the signal the
    /// generator uses to emit an "unrecognized structure" notice for anything else (whose docs degrade to
    /// their own coherently-titled band rather than a silent dump). Delegates to the rendering-core builder that
    /// now owns the group set (Story 6.2 relocated <c>KnownIndexGroups</c> there). [Story 4.2 Task 3/5]</summary>
    public static bool IsWellKnownTopLevelFolder(string folder) =>
        DashboardViewBuilder.IsWellKnownTopLevelFolder(folder);

    /// <summary>Builds the home dashboard page. The BODY is now decomposed into a host-neutral
    /// <see cref="DashboardView"/> (built by <see cref="DashboardViewBuilder"/>) and rendered to today's exact
    /// bytes by <see cref="HtmlRenderAdapter.RenderDashboardBody"/>; the shared chrome (head/nav/breadcrumb/
    /// footer) is assembled by the same adapter from the <see cref="PageView"/> — the DELIVERY-seam contract
    /// (AD-2). This is 6.1's opaque <see cref="PageView.BodyHtml"/> seam now carrying an adapter-rendered-from-data
    /// body instead of a templater-hand-built one; bytes unchanged. [Story 6.1; Story 6.2]</summary>
    public static string RenderIndex(IReadOnlyList<DocModel> docs, SiteNav nav, ProgressModel progress, EpicsModel? epicsModel, RequirementsModel? requirements, IReadOnlyList<AdrEntry> adrs, CommandCatalog commands, WorkInventory? work = null, SprintStatus? sprint = null, IReadOnlyList<RetroModel>? retros = null, ArtifactCoverage? coverage = null, bool hasTimeline = false, Func<string, string?>? codeItemHref = null, ProjectCounts? counts = null) =>
        HtmlRenderAdapter.Shared.Render(BuildIndexPage(docs, nav, progress, epicsModel, requirements, adrs, commands, work, sprint, retros, coverage, hasTimeline, codeItemHref, counts)).Content;

    /// <summary>Builds the dashboard's <see cref="PageView"/> without committing to a surface — the mechanical
    /// split of <see cref="RenderIndex"/> (which now just feeds this through the HTML adapter, bytes unchanged)
    /// that lets the webview surface render the SAME page model through its own <see cref="IRenderAdapter"/>
    /// instead of duplicating the view/PageView assembly. [Story 6.4]</summary>
    public static PageView BuildIndexPage(IReadOnlyList<DocModel> docs, SiteNav nav, ProgressModel progress, EpicsModel? epicsModel, RequirementsModel? requirements, IReadOnlyList<AdrEntry> adrs, CommandCatalog commands, WorkInventory? work = null, SprintStatus? sprint = null, IReadOnlyList<RetroModel>? retros = null, ArtifactCoverage? coverage = null, bool hasTimeline = false, Func<string, string?>? codeItemHref = null, ProjectCounts? counts = null)
    {
        var inventory = work ?? WorkInventory.Empty;

        var view = DashboardViewBuilder.Build(nav, progress, epicsModel, requirements, commands, inventory, sprint, coverage, hasTimeline, counts);
        var body = HtmlRenderAdapter.Shared.RenderDashboardBody(view, codeItemHref);

        // Home carries a descriptive title (sub-pages are already "Title — Site") + OG/description, no
        // breadcrumb, and its one drill child is the Epics index (when epics exist). [Story 1.5 G2; Story 6.1]
        var page = new PageView
        {
            Kind = PageKind.Home,
            OutputRelativePath = SiteNav.HomeOutputPath,
            Title = $"{nav.SiteTitle} — Project Dashboard",
            MetaDescription = $"Project dashboard and living documentation for {nav.SiteTitle}, generated by SpecScribe.",
            Nav = nav.ToNavigationView(SiteNav.HomeOutputPath),
            Breadcrumb = BreadcrumbTrail.Empty,
            Assets = new AssetManifest
            {
                StylesheetHref = ForgeOptions.StylesheetName,
                ScriptHref = ForgeOptions.ScriptName,
                MermaidNeeded = Mermaid.ContainsBlock(body),
            },
            Interaction = new InteractionState
            {
                ChildTargets = nav.HasEpics ? new[] { SiteNav.EpicsOutputPath } : Array.Empty<string>(),
            },
            BodyHtml = body,
        };
        return page;
    }

    private static void AppendPill(StringBuilder sb, string? value, string _)
    {
        if (string.IsNullOrEmpty(value)) return;
        sb.Append($"    <span class=\"pill\">{Html(value)}</span>\n");
    }

    private static void AppendPill(StringBuilder sb, string? value, Func<string, string> format)
    {
        if (string.IsNullOrEmpty(value)) return;
        sb.Append($"    <span class=\"pill\">{Html(format(value))}</span>\n");
    }

    private static void AppendStatusPill(StringBuilder sb, string? status)
    {
        if (string.IsNullOrEmpty(status)) return;
        var cls = "status-" + status.ToLowerInvariant().Replace(' ', '-');
        sb.Append($"    <span class=\"pill {Html(cls)}\">{Html(status)}</span>\n");
    }

    private static string Html(string s) => PathUtil.Html(s);
}
