using System.Text;

namespace SpecScribe;

/// <summary>Wraps rendered markdown bodies in full HTML pages, and builds the generated site's index.</summary>
public static class HtmlTemplater
{

    public static string RenderPage(DocModel doc, SiteNav nav)
    {
        var prefix = PathUtil.RelativePrefix(doc.OutputRelativePath);
        var cssHref = prefix + ForgeOptions.StylesheetName;

        var sb = new StringBuilder();
        sb.Append(PathUtil.RenderHeadOpen($"{doc.Title} — {nav.SiteTitle}", cssHref));
        sb.Append(nav.RenderNavBar(doc.OutputRelativePath));
        sb.Append(SiteNav.RenderBreadcrumb(doc.OutputRelativePath, new (string, string?)[] { ("Home", "index.html"), (doc.Title, null) }));

        sb.Append("<header class=\"doc-header\">\n");
        sb.Append($"  <h1>{Html(doc.Title)}</h1>\n");
        if (doc.Frontmatter.Project is { Length: > 0 } project)
        {
            sb.Append($"  <div class=\"doc-subtitle\">{Html(project)}</div>\n");
        }
        sb.Append("  <div class=\"meta-pills\">\n");
        AppendPill(sb, doc.Frontmatter.Author, "author");
        AppendPill(sb, doc.Frontmatter.Date, "date");
        AppendPill(sb, doc.Frontmatter.Version, v => $"v{v}");
        AppendStatusPill(sb, doc.Frontmatter.Status);
        sb.Append($"    <span class=\"pill\">{Html(PathUtil.NormalizeSlashes(doc.SourceRelativePath))}</span>\n");
        sb.Append("  </div>\n</header>\n\n");

        var tocHeadings = doc.Headings.Where(h => h.Level is 2 or 3).ToList();
        if (tocHeadings.Count > 0)
        {
            sb.Append("<nav class=\"toc-strip\" aria-label=\"On this page\">\n");
            sb.Append("  <span class=\"toc-label\">On this page</span>\n");
            foreach (var h in tocHeadings)
            {
                var cls = h.Level == 3 ? " toc-h3" : string.Empty;
                sb.Append($"  <a class=\"{cls.Trim()}\" href=\"#{Html(h.Id)}\">{Html(h.Text)}</a>\n");
            }
            sb.Append("</nav>\n\n");
        }

        sb.Append("<article class=\"doc-body\">\n");
        sb.Append(doc.BodyHtml);
        sb.Append("\n</article>\n\n");

        sb.Append(PathUtil.RenderFooter($"Auto-generated by SpecScribe from <code>{Html(PathUtil.NormalizeSlashes(doc.SourceRelativePath))}</code> &middot; {DateTime.Now:yyyy-MM-dd HH:mm}"));
        if (doc.HasMermaid)
        {
            sb.Append(Mermaid.InitScript());
        }
        sb.Append("</body>\n</html>\n");
        return sb.ToString();
    }

    public static string RenderIndex(IReadOnlyList<DocModel> docs, SiteNav nav, ProgressModel progress, EpicsModel? epicsModel, RequirementsModel? requirements, IReadOnlyList<AdrEntry> adrs)
    {
        var groups = new (string Title, string Prefix)[]
        {
            ("Overview", ""),
            ("Planning Artifacts", "planning-artifacts"),
            ("Implementation Artifacts", "implementation-artifacts"),
        };

        var sb = new StringBuilder();
        sb.Append(PathUtil.RenderHeadOpen($"{nav.SiteTitle} — Live Docs", ForgeOptions.StylesheetName));
        sb.Append(nav.RenderNavBar(SiteNav.HomeOutputPath));

        sb.Append("<header class=\"doc-header\">\n");
        sb.Append($"  <h1>{Html(nav.SiteTitle)}</h1>\n");
        sb.Append("  <div class=\"doc-subtitle\">Live Docs — auto-generated from _bmad-output on every save</div>\n");
        sb.Append("</header>\n\n");

        AppendDashboard(sb, progress, epicsModel, requirements);

        var used = new HashSet<DocModel>();
        foreach (var (groupTitle, groupPrefix) in groups)
        {
            var inGroup = docs
                .Where(d => !used.Contains(d))
                .Where(d => groupPrefix.Length == 0
                    ? !PathUtil.NormalizeSlashes(d.SourceRelativePath).Contains('/')
                    : PathUtil.NormalizeSlashes(d.SourceRelativePath).StartsWith(groupPrefix + "/", StringComparison.OrdinalIgnoreCase))
                .OrderBy(d => d.Title, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (inGroup.Count == 0) continue;
            foreach (var d in inGroup) used.Add(d);

            sb.Append($"<div class=\"index-section-title\">{Html(groupTitle)}</div>\n");
            sb.Append("<div class=\"index-grid\">\n");
            foreach (var d in inGroup)
            {
                AppendIndexCard(sb, d);
            }
            sb.Append("</div>\n\n");
        }

        var remaining = docs.Where(d => !used.Contains(d)).OrderBy(d => d.Title, StringComparer.OrdinalIgnoreCase).ToList();
        if (remaining.Count > 0)
        {
            sb.Append("<div class=\"index-section-title\">Other</div>\n<div class=\"index-grid\">\n");
            foreach (var d in remaining)
            {
                AppendIndexCard(sb, d);
            }
            sb.Append("</div>\n\n");
        }

        AppendAdrSection(sb, adrs);

        sb.Append(PathUtil.RenderFooter($"{Html(nav.SiteTitle)} &middot; Live Docs &middot; last rebuilt {DateTime.Now:yyyy-MM-dd HH:mm}"));
        sb.Append("</body>\n</html>\n");
        return sb.ToString();
    }

    private static void AppendDashboard(StringBuilder sb, ProgressModel p, EpicsModel? epicsModel, RequirementsModel? requirements)
    {
        sb.Append("<section class=\"dashboard\">\n");

        sb.Append("<div class=\"stat-grid\">\n");
        sb.Append(Charts.StatCard($"{p.EpicsDrafted}/{p.EpicsTotal}", "Epics drafted"));
        sb.Append(Charts.StatCard(p.StoriesTotal.ToString(), "Stories defined", $"{p.StoriesWithArtifact} with a task plan"));
        sb.Append(p.TasksTotal > 0
            ? Charts.StatCard($"{p.TasksDone}/{p.TasksTotal}", "Tasks done", $"across {p.StoriesWithArtifact} of {p.StoriesTotal} stories")
            : Charts.StatCard("—", "Tasks done", "none tracked yet"));
        sb.Append(p.Git is { } git
            ? Charts.StatCard(git.TotalCommits.ToString(), "Commits", $"{git.ActiveDays} active day{(git.ActiveDays == 1 ? "" : "s")}")
            : Charts.StatCard("—", "Commits", "no git history"));
        sb.Append("</div>\n\n");

        sb.Append("<div class=\"chart-panel\">\n<h3>Overall Progress</h3>\n");
        sb.Append(Charts.ProgressBar("Planning", p.EpicsDrafted, p.EpicsTotal, $"{p.EpicsDrafted} / {p.EpicsTotal} epics"));
        sb.Append(p.TasksTotal > 0
            ? Charts.ProgressBar("Implementation", p.TasksDone, p.TasksTotal, $"{p.TasksDone} / {p.TasksTotal} tasks ({p.StoriesWithArtifact} of {p.StoriesTotal} stories planned)")
            : Charts.ProgressBar("Implementation", 0, 0, "not started"));
        sb.Append("</div>\n\n");

        if (epicsModel is not null)
        {
            AppendNowAndNext(sb, epicsModel);

            // The sunburst sits immediately under Now & Next — the "where do I look" panel and the
            // whole-project map read as a pair, so keep them adjacent rather than separated by the
            // status donuts and requirements panels.
            // The dedicated "Epics & Stories" index card felt redundant once the whole dashboard was
            // effectively an epics/stories overview — this CTA lives where the sunburst already is one.
            sb.Append("<div class=\"chart-panel sunburst-panel\">\n");
            sb.Append("<div class=\"chart-panel-header-row\"><h3>Project at a Glance</h3>");
            sb.Append("<a class=\"view-epic-link\" href=\"epics.html\">View Epics &amp; Stories &rarr;</a></div>\n");
            sb.Append(Charts.Sunburst(epicsModel));
            sb.Append("</div>\n\n");

            sb.Append(BmadCommands.RenderProjectNextSteps(epicsModel));
        }

        sb.Append("<div class=\"chart-row\">\n");

        sb.Append("<div class=\"chart-panel\">\n<h3>Epic Status</h3>\n<div class=\"donut-and-legend\">\n");
        sb.Append(Charts.Donut(new (string, int, string)[]
        {
            ("Drafted", p.EpicsDrafted, "drafted"),
            ("Pending", p.EpicsPending, "pending"),
        }));
        sb.Append("<div class=\"donut-legend\">\n");
        sb.Append($"  <span><span class=\"swatch drafted\"></span>Drafted ({p.EpicsDrafted})</span>\n");
        sb.Append($"  <span><span class=\"swatch pending\"></span>Pending ({p.EpicsPending})</span>\n");
        sb.Append("</div>\n</div>\n</div>\n\n");

        sb.Append("<div class=\"chart-panel\">\n<h3>Commit Activity</h3>\n");
        sb.Append(p.Git is { } gitPulse
            ? Charts.CommitHeatmap(gitPulse.DailySeries)
            : "<div class=\"chart-empty\">No git history available.</div>\n");
        sb.Append("</div>\n\n");

        sb.Append("</div>\n\n");

        AppendRequirementsPanel(sb, requirements);

        if (p.PerEpic.Count > 0)
        {
            sb.Append("<div class=\"chart-panel\">\n<h3>Progress by Epic</h3>\n");
            sb.Append(Charts.EpicMosaic(p.PerEpic, e => $"epics/epic-{e.Number}.html"));
            sb.Append("</div>\n\n");
        }

        sb.Append("</section>\n\n");
    }

    /// <summary>FR/NFR progress at a glance: a status donut for each kind, rolled up from covering-epic
    /// progress, with a CTA into the full requirements page.</summary>
    private static void AppendRequirementsPanel(StringBuilder sb, RequirementsModel? requirements)
    {
        if (requirements is null || !requirements.All.Any()) return;

        sb.Append("<div class=\"chart-panel\">\n");
        sb.Append("<div class=\"chart-panel-header-row\"><h3>Requirements Progress</h3>");
        sb.Append("<a class=\"view-epic-link\" href=\"requirements.html\">View Requirements &rarr;</a></div>\n");
        sb.Append("<div class=\"chart-row\">\n");
        AppendRequirementDonut(sb, "Functional", requirements.Functional);
        AppendRequirementDonut(sb, "Non-functional", requirements.NonFunctional);
        sb.Append("</div>\n</div>\n\n");
    }

    private static void AppendRequirementDonut(StringBuilder sb, string label, IReadOnlyList<RequirementInfo> reqs)
    {
        int done = reqs.Count(r => r.Status == RequirementStatus.Done);
        int ready = reqs.Count(r => r.Status == RequirementStatus.Ready);
        int planned = reqs.Count(r => r.Status == RequirementStatus.Planned);
        int deferred = reqs.Count(r => r.Status == RequirementStatus.Deferred);

        sb.Append("<div class=\"chart-col\">\n");
        sb.Append($"  <div class=\"req-donut-label\">{Html(label)} ({reqs.Count})</div>\n");
        sb.Append("  <div class=\"donut-and-legend\">\n");
        sb.Append(Charts.Donut(new (string, int, string)[]
        {
            ("Done", done, "done"),
            ("Ready for dev", ready, "ready"),
            ("Planned", planned, "pending"),
            ("Deferred", deferred, "deferred"),
        }));
        sb.Append("<div class=\"donut-legend\">\n");
        sb.Append($"  <span><span class=\"swatch done\"></span>Done ({done})</span>\n");
        sb.Append($"  <span><span class=\"swatch ready\"></span>Ready ({ready})</span>\n");
        sb.Append($"  <span><span class=\"swatch pending\"></span>Planned ({planned})</span>\n");
        sb.Append($"  <span><span class=\"swatch deferred\"></span>Deferred ({deferred})</span>\n");
        sb.Append("</div>\n  </div>\n</div>\n");
    }

    /// <summary>Surfaces what's in motion right now: stories in dev, stories ready to start, and the
    /// next epic awaiting story breakdown — the "where do I look next" panel.</summary>
    private static void AppendNowAndNext(StringBuilder sb, EpicsModel epicsModel)
    {
        var allStories = epicsModel.Epics.SelectMany(e => e.Stories.Select(s => (Epic: e, Story: s))).ToList();
        var inDev = allStories.Where(x => StatusStyles.ForStory(x.Story) == "active").ToList();
        var inReview = allStories.Where(x => StatusStyles.ForStory(x.Story) == "review").ToList();
        var upNext = allStories.Where(x => StatusStyles.ForStory(x.Story) == "ready").ToList();

        // The lowest-numbered story that's been listed in a drafted epic but has no artifact yet — the
        // next stub to flesh out. Pending epics are covered by nextEpicToDraft, so exclude them here.
        var nextStoryToDraft = allStories
            .Where(x => x.Epic.Status == EpicStatus.Drafted && StatusStyles.ForStory(x.Story) == "drafted")
            .OrderBy(x => x.Epic.Number)
            .ThenBy(x => StoryMinor(x.Story.Id))
            .Select(x => (x.Epic, x.Story))
            .FirstOrDefault();

        var nextEpicToDraft = epicsModel.Epics.OrderBy(e => e.Number).FirstOrDefault(e => e.Status == EpicStatus.Pending);

        if (inDev.Count == 0 && inReview.Count == 0 && upNext.Count == 0
            && nextStoryToDraft.Story is null && nextEpicToDraft is null) return;

        sb.Append("<div class=\"chart-panel\">\n<h3>Now &amp; Next</h3>\n<div class=\"now-next\">\n");

        foreach (var (epic, story) in inDev)
        {
            AppendNowNextCard(sb, "active", "In development",
                $"Story {story.Id} · {PathUtil.StripHtmlTags(story.Title)}",
                story.ArtifactOutputPath ?? $"epics/epic-{epic.Number}.html");
        }

        foreach (var (epic, story) in inReview)
        {
            AppendNowNextCard(sb, "review", "In review",
                $"Story {story.Id} · {PathUtil.StripHtmlTags(story.Title)}",
                story.ArtifactOutputPath ?? $"epics/epic-{epic.Number}.html");
        }

        foreach (var (epic, story) in upNext)
        {
            AppendNowNextCard(sb, "ready", "Up next",
                $"Story {story.Id} · {PathUtil.StripHtmlTags(story.Title)}",
                story.ArtifactOutputPath ?? $"epics/epic-{epic.Number}.html");
        }

        if (nextStoryToDraft.Story is not null)
        {
            var (epic, story) = nextStoryToDraft;
            AppendNowNextCard(sb, "drafted", "Next story to draft",
                $"Story {story.Id} · {PathUtil.StripHtmlTags(story.Title)}",
                story.ArtifactOutputPath ?? $"epics/epic-{epic.Number}.html");
        }

        if (nextEpicToDraft is not null)
        {
            AppendNowNextCard(sb, "pending", "Next epic to draft",
                $"Epic {nextEpicToDraft.Number} · {PathUtil.StripHtmlTags(nextEpicToDraft.Title)}",
                $"epics/epic-{nextEpicToDraft.Number}.html");
        }

        sb.Append("</div>\n</div>\n\n");
    }

    /// <summary>The "M" from a story id "N.M", for ordering stories within an epic; falls back to
    /// <see cref="int.MaxValue"/> for ids that don't parse so they sort last rather than throw.</summary>
    private static int StoryMinor(string storyId)
    {
        var dot = storyId.LastIndexOf('.');
        return dot >= 0 && int.TryParse(storyId.AsSpan(dot + 1), out var minor) ? minor : int.MaxValue;
    }

    private static void AppendNowNextCard(StringBuilder sb, string cssClass, string kicker, string title, string href)
    {
        sb.Append($"  <a class=\"now-next-card {cssClass}\" href=\"{Html(href)}\">\n");
        sb.Append($"    <span class=\"now-next-kicker\">{Html(kicker)}</span>\n");
        sb.Append($"    <span class=\"now-next-title\">{Html(title)}</span>\n");
        sb.Append("  </a>\n");
    }

    /// <summary>The "Architecture Decision Records" band on the home index: a titled section with a link to the
    /// ADR landing page and one card per numbered record. Omitted entirely when there are no ADRs.</summary>
    private static void AppendAdrSection(StringBuilder sb, IReadOnlyList<AdrEntry> adrs)
    {
        if (adrs.Count == 0) return;

        sb.Append("<div class=\"index-section-title-row\">\n");
        sb.Append("  <span class=\"index-section-title\">Architecture Decision Records</span>\n");
        sb.Append($"  <a class=\"view-epic-link\" href=\"{Html(SiteNav.AdrsLandingOutputPath)}\">All ADRs &rarr;</a>\n");
        sb.Append("</div>\n");

        sb.Append("<div class=\"index-grid\">\n");
        foreach (var adr in adrs)
        {
            AppendAdrCard(sb, adr);
        }
        sb.Append("</div>\n\n");
    }

    private static void AppendAdrCard(StringBuilder sb, AdrEntry adr)
    {
        sb.Append($"  <a class=\"index-card\" href=\"{Html(PathUtil.NormalizeSlashes(adr.OutputRelativePath))}\">\n");
        sb.Append($"    <h2>{Html(adr.Title)}</h2>\n");
        if (adr.Status is { Length: > 0 } status)
        {
            var cls = "status-" + status.Split(' ')[0].ToLowerInvariant().Replace(' ', '-');
            sb.Append($"    <p><span class=\"pill {Html(cls)}\">{Html(status)}</span></p>\n");
        }
        sb.Append($"    <span class=\"index-card-path\">{Html(PathUtil.NormalizeSlashes(adr.SourceRelativePath))}</span>\n");
        sb.Append("  </a>\n");
    }

    private static void AppendIndexCard(StringBuilder sb, DocModel d)
    {
        var href = PathUtil.NormalizeSlashes(d.OutputRelativePath);
        sb.Append($"  <a class=\"index-card\" href=\"{Html(href)}\">\n");
        sb.Append($"    <h2>{Html(d.Title)}</h2>\n");

        var descParts = new List<string>();
        if (d.Frontmatter.Status is { Length: > 0 } s) descParts.Add(s);
        if (d.Frontmatter.Date is { Length: > 0 } dt) descParts.Add(dt);
        if (d.Frontmatter.Author is { Length: > 0 } a) descParts.Add(a);
        if (descParts.Count > 0)
        {
            sb.Append($"    <p>{Html(string.Join(" · ", descParts))}</p>\n");
        }

        sb.Append($"    <span class=\"index-card-path\">{Html(PathUtil.NormalizeSlashes(d.SourceRelativePath))}</span>\n");
        sb.Append("  </a>\n");
    }

    private static void AppendPill(StringBuilder sb, string? value, string _)
    {
        if (string.IsNullOrEmpty(value)) return;
        sb.Append($"    <span class=\"pill\">{Html(value)}</span>\n");
    }

    private static void AppendPill(StringBuilder sb, string? value, Func<string, string> format)
    {
        if (string.IsNullOrEmpty(value)) return;
        sb.Append($"    <span class=\"pill\">{Html(format(value))}</span>\n");
    }

    private static void AppendStatusPill(StringBuilder sb, string? status)
    {
        if (string.IsNullOrEmpty(status)) return;
        var cls = "status-" + status.ToLowerInvariant().Replace(' ', '-');
        sb.Append($"    <span class=\"pill {Html(cls)}\">{Html(status)}</span>\n");
    }

    private static string Html(string s) => PathUtil.Html(s);
}
