<script setup lang="ts">
/**
 * The page shell — header / main / footer chrome, reused by every route.
 *
 * Carries the two accessibility contracts every SpecScribe page has held since Story 1.4: a skip link as
 * the first focusable element, and a `#main-content` landmark for it to target (UX-DR16). Putting them in
 * the shell means a new route cannot forget them.
 *
 * `<main>` sits OUTSIDE the scoped-style boundary problem 23.3 hit: content injected there with `v-html` is
 * not stamped with this SFC's `data-v-*` attribute, so the rules below will not reach it.
 * See CONVENTIONS.md, "Styling injected content".
 */
import { onMounted } from 'vue'

const props = withDefaults(
  defineProps<{
    /**
     * The page's title. Rendered as the h1 under `chrome: 'full'`; under `chrome: 'nav-only'` the injected
     * IR content owns the h1 and this is used only by the caller's head projection.
     */
    title: string
    /** One-line orientation under the title. Ignored under `chrome: 'nav-only'`. */
    subtitle?: string
    /** The kicker above the title — the site/brand line. Ignored under `chrome: 'nav-only'`. */
    brand?: string
    /**
     * How much chrome the shell supplies. [Story 23.3]
     *
     * `full` — the app's own routes: brand, h1, subtitle, and a reading-width column.
     * `nav-only` — an IR-backed route: the injected content already carries the site nav, its own h1 and
     *   its own layout, so the shell contributes only the skip link and gets out of the way. Adding a
     *   second h1 and a 64rem column on top of a full-bleed dashboard would be a regression dressed as
     *   consistency.
     *
     * Under `nav-only` the shell also does NOT emit `<main>` — the caller supplies it through `IrMain`,
     * which reproduces the golden page's open tag exactly. A `<main>` authored HERE would carry this SFC's
     * `data-v-*` attribute and bracket its slot content in Vue's `<!--[-->` fragment anchors: 32 bytes of
     * hydration bookkeeping inside the one region Story 23.3 compares byte-for-byte. See `IrMain.ts`.
     */
    chrome?: 'full' | 'nav-only'
  }>(),
  { subtitle: undefined, brand: 'SpecScribe', chrome: 'full' },
)

/**
 * The skip link is emitted unconditionally; `<main id="main-content">` is emitted only under `chrome: 'full'`.
 * That asymmetry is CORRECT — under `nav-only` the caller owns the landmark (`IrMain`) — but nothing checked
 * that the caller actually supplied one, so a `nav-only` consumer that forgot it shipped a skip link pointing
 * at an id that does not exist: the link focuses, and activating it goes nowhere. Silent, and invisible to
 * SSR-only tests. `chrome` is union-erased too, and `chrome === 'full'` is the only test in the template, so
 * ANY out-of-vocabulary value selects the `nav-only` branch and lands in exactly this hole.
 * [Story 23.2 review 2026-08-07]
 */
if (import.meta.dev) {
  if (props.chrome !== 'full' && props.chrome !== 'nav-only') {
    console.warn(
      `[PageShell] unknown chrome "${props.chrome}" — every value that is not "full" renders the bare shell, ` +
        `which does NOT emit <main id="main-content">. Use "full" or "nav-only".`,
    )
  }
  if (props.chrome !== 'full') {
    onMounted(() => {
      if (!document.getElementById('main-content')) {
        console.warn(
          `[PageShell] chrome="${props.chrome}" does not emit <main id="main-content">, and the slot content ` +
            `did not supply one either — so this page's skip link targets a missing id and goes nowhere ` +
            `(UX-DR16). Render the landmark via <IrMain>, or use chrome="full".`,
        )
      }
    })
  }
}
</script>

<template>
  <div class="shell" :class="{ 'shell-bare': chrome === 'nav-only' }">
    <a class="skip-link" href="#main-content">Skip to main content</a>

    <header v-if="chrome === 'full'" class="shell-head">
      <p class="shell-brand">{{ brand }}</p>
      <h1 class="shell-title">{{ title }}</h1>
      <p v-if="subtitle" class="shell-subtitle">{{ subtitle }}</p>
      <slot name="nav" />
    </header>
    <slot v-else name="nav" />

    <main v-if="chrome === 'full'" id="main-content">
      <slot />
    </main>
    <slot v-else />

    <footer class="shell-foot">
      <slot name="footer">
        <p>Generated by SpecScribe.</p>
      </slot>
    </footer>
  </div>
</template>

<style scoped>
.shell {
  max-width: 64rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem 4rem;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

/* NOTE: `.skip-link` has NO rule here, and must not gain one. [Story 23.2 review 2026-08-07]
   It is a SHARED PRIMITIVE (ADR 0029): the single definition lives in `specscribe.css` and is emitted
   unscoped into `web/assets/shared-primitives.css`, which reaches this component's template-authored anchor.
   A scoped copy here previously tied on specificity (0,2,0) with the generated `.ir-content .skip-link` —
   because `IrSurface` puts `class="ir-content"` on this component's own root — so the winner was decided by
   chunk order. If PageShell won, its `z-index: 10` sat beneath the sticky nav's 100 and the focused link was
   invisible; if the generated rule won, `position: absolute` came back and the link rendered at the top of
   the DOCUMENT rather than the viewport. Re-adding a rule here reinstates that race.
   The `fixed`-not-`absolute` reasoning that the 2026-07-28 re-review established now lives on the source
   rule in `specscribe.css`, where it protects both surfaces instead of one. */

.shell-head {
  border-bottom: 2px solid var(--border);
  padding-bottom: 0.9rem;
  margin-bottom: 1.5rem;
}

.shell-brand {
  font-size: 0.72rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--ink-light);
  margin: 0;
}

.shell-title {
  font-size: 1.9rem;
  color: var(--ink);
  margin: 0.15rem 0 0;
  line-height: 1.2;
}

.shell-subtitle {
  color: var(--ink-faded);
  font-size: 0.95rem;
  margin: 0.35rem 0 0;
  max-width: 46rem;
  text-wrap: pretty;
}

/* Selected by ELEMENT, not by a `shell-main` class, so the rule reads the same for both chrome modes. An
   IR route's `<main>` comes from `IrMain` and carries no `data-v-*`, so this scoped rule does NOT reach it
   — `assets/base.css` carries the equivalent for `.shell-bare > main`. */
.shell > main {
  flex: 1 0 auto;
  /* The entrance every surface shares, expressed only through motion tokens. The global reduce block in
     base.css neutralises it — this component declares no second reduced-motion rule of its own. */
  animation: shell-fade var(--motion-entrance) var(--motion-ease) both;
}

/* An IR-backed route: no reading-width column, no page padding. The injected content is a whole page's
   worth of layout authored against the portal's own stylesheet, and constraining it here would collapse
   full-bleed surfaces like the dashboard. */
.shell-bare {
  max-width: none;
  padding: 0;
}

.shell-foot {
  margin-top: 2.5rem;
  padding-top: 0.9rem;
  border-top: 1px solid var(--border);
  color: var(--ink-light);
  font-size: 0.78rem;
}

@keyframes shell-fade {
  from {
    opacity: 0;
    transform: translateY(0.4rem);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
</style>
