<script setup lang="ts">
/**
 * The page shell — header / main / footer chrome, reused by every route.
 *
 * Carries the two accessibility contracts every SpecScribe page has held since Story 1.4: a skip link as
 * the first focusable element, and a `#main-content` landmark for it to target (UX-DR16). Putting them in
 * the shell means a new route cannot forget them.
 *
 * `<main>` sits OUTSIDE the scoped-style boundary problem 23.3 will hit: content injected there with
 * `v-html` is not stamped with this SFC's `data-v-*` attribute, so the rules below will not reach it.
 * See CONVENTIONS.md, "Styling injected content".
 */
withDefaults(
  defineProps<{
    /** The page's h1. */
    title: string
    /** One-line orientation under the title. */
    subtitle?: string
    /** The kicker above the title — the site/brand line. */
    brand?: string
  }>(),
  { subtitle: undefined, brand: 'SpecScribe' },
)
</script>

<template>
  <div class="shell">
    <a class="skip-link" href="#main-content">Skip to main content</a>

    <header class="shell-head">
      <p class="shell-brand">{{ brand }}</p>
      <h1 class="shell-title">{{ title }}</h1>
      <p v-if="subtitle" class="shell-subtitle">{{ subtitle }}</p>
      <slot name="nav" />
    </header>

    <main id="main-content" class="shell-main">
      <slot />
    </main>

    <footer class="shell-foot">
      <slot name="footer">
        <p>Generated by SpecScribe.</p>
      </slot>
    </footer>
  </div>
</template>

<style scoped>
.shell {
  max-width: 64rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem 4rem;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

/* Visually hidden until focused, then pinned so a keyboard user can jump past the header. */
.skip-link {
  position: absolute;
  left: -9999px;
  top: 0;
  background: var(--warm-white);
  color: var(--ink);
  border: 1px solid var(--border);
  padding: 0.5rem 0.9rem;
  z-index: 10;
}

.skip-link:focus {
  left: 0.5rem;
  top: 0.5rem;
}

.shell-head {
  border-bottom: 2px solid var(--border);
  padding-bottom: 0.9rem;
  margin-bottom: 1.5rem;
}

.shell-brand {
  font-size: 0.72rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--ink-light);
  margin: 0;
}

.shell-title {
  font-size: 1.9rem;
  color: var(--ink);
  margin: 0.15rem 0 0;
  line-height: 1.2;
}

.shell-subtitle {
  color: var(--ink-faded);
  font-size: 0.95rem;
  margin: 0.35rem 0 0;
  max-width: 46rem;
  text-wrap: pretty;
}

.shell-main {
  flex: 1 0 auto;
  /* The entrance every surface shares, expressed only through motion tokens. The global reduce block in
     base.css neutralises it — this component declares no second reduced-motion rule of its own. */
  animation: shell-fade var(--motion-entrance) var(--motion-ease) both;
}

.shell-foot {
  margin-top: 2.5rem;
  padding-top: 0.9rem;
  border-top: 1px solid var(--border);
  color: var(--ink-light);
  font-size: 0.78rem;
}

@keyframes shell-fade {
  from {
    opacity: 0;
    transform: translateY(0.4rem);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
</style>
